// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBjZYREBfP_QgkLGQJmCuWjBXCPHhLnk',
    appId: '1:1064550272009:web:fbf2db6ee03515b9867cd8',
    messagingSenderId: '1064550272009',
    projectId: 'myhabits2-flutter',
    authDomain: 'myhabits2-flutter.firebaseapp.com',
    storageBucket: 'myhabits2-flutter.appspot.com',
    measurementId: 'G-SCDW2MQ9WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6zFUVu39OuIYaefNjIRLwR0dekKe5Tp4',
    appId: '1:1064550272009:android:ecea3032478574cb867cd8',
    messagingSenderId: '1064550272009',
    projectId: 'myhabits2-flutter',
    storageBucket: 'myhabits2-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-0yvrg6OBcFHsk1dDhYHpetq5E_zN1E',
    appId: '1:1064550272009:ios:55bdb8ab1cbe1679867cd8',
    messagingSenderId: '1064550272009',
    projectId: 'myhabits2-flutter',
    storageBucket: 'myhabits2-flutter.appspot.com',
    iosClientId: '1064550272009-3p5o962ag73175o4r5dovie31rutjrl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhabitsv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-0yvrg6OBcFHsk1dDhYHpetq5E_zN1E',
    appId: '1:1064550272009:ios:55bdb8ab1cbe1679867cd8',
    messagingSenderId: '1064550272009',
    projectId: 'myhabits2-flutter',
    storageBucket: 'myhabits2-flutter.appspot.com',
    iosClientId: '1064550272009-3p5o962ag73175o4r5dovie31rutjrl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhabitsv2',
  );
}
